import pandas as pd

# This creates the structure T5 needs: 'input' with prefix and 'target'
data = {
    "input": [
        "gec: He go to school yesterday.",
        "gec: I has a apple.",
        "gec: The weather are nice today.",
        "gec: We was walking to the store.",
        "gec: Learn !",
        "gec: He go to school yesterday.",
        "gec: I has a apple.",
        "gec: The weather are nice today.",
        "gec: We was walking to the store.",
        "gec: Learn !",
        "gec: He go to school yesterday.",
        "gec: I has a apple.",
        "gec: The weather are nice today.",
        "gec: We was walking to the store.",
        "gec: Learn !",
        "gec: He go to school yesterday.",
        "gec: I has a apple.",
        "gec: The weather are nice today.",
        "gec: We was walking to the store.",
        "gec: Learn !",
        "gec: He go to school yesterday.",
        "gec: I has a apple.",
        "gec: The weather are nice today.",
        "gec: We was walking to the store.",
        "gec: Learn !",
        "gec: He go to school yesterday.",
        "gec: I has a apple.",
        "gec: The weather are nice today.",
        "gec: We was walking to the store.",
        "gec: Learn !",
        "gec: He go to school yesterday.",
        "gec: I has a apple.",
        "gec: The weather are nice today.",
        "gec: We was walking to the store.",
        "gec: Learn !",
        "gec: He go to school yesterday.",
        "gec: I has a apple.",
        "gec: The weather are nice today.",
        "gec: We was walking to the store.",
        "gec: Learn !",
        "gec: He go to school yesterday.",
        "gec: I has a apple.",
        "gec: The weather are nice today.",
        "gec: We was walking to the store.",
        "gec: Learn !",
        "gec: He go to school yesterday.",
        "gec: I has a apple.",
        "gec: The weather are nice today.",
        "gec: We was walking to the store.",
        "gec: Learn !",
        "gec: He go to school yesterday.",
        "gec: I has a apple.",
        "gec: The weather are nice today.",
        "gec: We was walking to the store.",
        "gec: Learn !",
        "gec: He go to school yesterday.",
        "gec: I has a apple.",
        "gec: The weather are nice today.",
        "gec: We was walking to the store.",
        "gec: Learn !",
        "gec: He go to school yesterday.",
        "gec: I has a apple.",
        "gec: The weather are nice today.",
        "gec: We was walking to the store.",
        "gec: Learn !",
        "gec: He go to school yesterday.",
        "gec: I has a apple.",
        "gec: The weather are nice today.",
        "gec: We was walking to the store.",
        "gec: Learn !",
        "gec: He go to school yesterday.",
        "gec: I has a apple.",
        "gec: The weather are nice today.",
        "gec: We was walking to the store.",
        "gec: Learn !",
        "gec: He go to school yesterday.",
        "gec: I has a apple.",
        "gec: The weather are nice today.",
        "gec: We was walking to the store.",
        "gec: Learn !",
        "gec: He go to school yesterday.",
        "gec: I has a apple.",
        "gec: The weather are nice today.",
        "gec: We was walking to the store.",
        "gec: Learn !",
        "gec: He go to school yesterday.",
        "gec: I has a apple.",
        "gec: The weather are nice today.",
        "gec: We was walking to the store.",
        "gec: Learn !",
        "gec: He go to school yesterday.",
        "gec: I has a apple.",
        "gec: The weather are nice today.",
        "gec: We was walking to the store.",
        "gec: Learn !",
        "gec: He go to school yesterday.",
        "gec: I has a apple.",
        "gec: The weather are nice today.",
        "gec: We was walking to the store.",
        "gec: Learn !"
    ],
    "target": [
        "He went to school yesterday.",
        "I have an apple.",
        "The weather is nice today.",
        "We are walking to the store.",
        "Earn !",
        "He went to school yesterday.",
        "I have an apple.",
        "The weather is nice today.",
        "We are walking to the store.",
        "Earn !",
        "He went to school yesterday.",
        "I have an apple.",
        "The weather is nice today.",
        "We are walking to the store.",
        "Earn !",
        "He went to school yesterday.",
        "I have an apple.",
        "The weather is nice today.",
        "We are walking to the store.",
        "Earn !",
        "He went to school yesterday.",
        "I have an apple.",
        "The weather is nice today.",
        "We are walking to the store.",
        "Earn !",
        "He went to school yesterday.",
        "I have an apple.",
        "The weather is nice today.",
        "We are walking to the store.",
        "Earn !",
        "He went to school yesterday.",
        "I have an apple.",
        "The weather is nice today.",
        "We are walking to the store.",
        "Earn !",
        "He went to school yesterday.",
        "I have an apple.",
        "The weather is nice today.",
        "We are walking to the store.",
        "Earn !",
        "He went to school yesterday.",
        "I have an apple.",
        "The weather is nice today.",
        "We are walking to the store.",
        "Earn !",
        "He went to school yesterday.",
        "I have an apple.",
        "The weather is nice today.",
        "We are walking to the store.",
        "Earn !",
        "He went to school yesterday.",
        "I have an apple.",
        "The weather is nice today.",
        "We are walking to the store.",
        "Earn !",
        "He went to school yesterday.",
        "I have an apple.",
        "The weather is nice today.",
        "We are walking to the store.",
        "Earn !",
        "He went to school yesterday.",
        "I have an apple.",
        "The weather is nice today.",
        "We are walking to the store.",
        "Earn !",
        "He went to school yesterday.",
        "I have an apple.",
        "The weather is nice today.",
        "We are walking to the store.",
        "Earn !",
        "He went to school yesterday.",
        "I have an apple.",
        "The weather is nice today.",
        "We are walking to the store.",
        "Earn !",
        "He went to school yesterday.",
        "I have an apple.",
        "The weather is nice today.",
        "We are walking to the store.",
        "Earn !",
        "He went to school yesterday.",
        "I have an apple.",
        "The weather is nice today.",
        "We are walking to the store.",
        "Earn !",
        "He went to school yesterday.",
        "I have an apple.",
        "The weather is nice today.",
        "We are walking to the store.",
        "Earn !",
        "He went to school yesterday.",
        "I have an apple.",
        "The weather is nice today.",
        "We are walking to the store.",
        "Earn !",
        "He went to school yesterday.",
        "I have an apple.",
        "The weather is nice today.",
        "We are walking to the store.",
        "Earn !",
    ]
}

df = pd.DataFrame(data)
df.to_csv("train.csv", index=False)
print("Step 1 Complete: train.csv created.")